version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - rust-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.${ENV:-dev}
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - cargo-registry:/usr/local/cargo/registry
    environment:
      - RUST_LOG=debug
      - PORT=3000
    restart: unless-stopped
    networks:
      - rust-network

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"  # HTTP API
      - "9000:9000"  # Native protocol
    volumes:
      - ./clickhouse_data/data:/var/lib/clickhouse  # Local folder for data
      # - ./clickhouse_data/config:/etc/clickhouse-server/config.d  # Custom configs
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=password
    networks:
      - rust-network
    healthcheck:
      test: ["CMD-SHELL", "wget -O - http://localhost:8123/ping || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  cargo-registry:
  clickhouse_data:
  clickhouse_config:

networks:
  rust-network:
    driver: bridge